//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelsManager
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.UploadedFiles = new HashSet<UploadedFile>();
            this.Reservations = new HashSet<Reservation>();
        }

        public int IDHotel { get; set; }

        [Required]
        [MaxLength(50, ErrorMessage = "Address must be at most 50 chars.")]
        public string Address { get; set; }

        [Required]
        [MaxLength(20, ErrorMessage = "City must be at most 20 chars.")]
        public string City { get; set; }

        [Required]
        [MaxLength(50, ErrorMessage = "Contact must be at most 50 chars.")]
        public string Contact { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UploadedFile> UploadedFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
