//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelsManager
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Reservation
    {
        public int IDReservation { get; set; }

        [Required]
        [DataType(DataType.Date, ErrorMessage = "Wrong date format.")]
        public string FromDate { get; set; }

        [Required]
        [DataType(DataType.Date, ErrorMessage = "Wrong date format.")]
        public string ToDate { get; set; }

        [Required]
        public int HotelIDHotel { get; set; }

        [Required]
        public int PersonIDPerson { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Person Person { get; set; }
    }
}
